protected/models/Post.php
<?php

/**
 * This is the model class for table "post".
 * @property integer $id
 * @property string  $autor
 * @property string  $text
 * @property string  $date
 * @property integer $lft
 * @property integer $rgt
 * @property integer $level
 * @property string  $alias
 * @property integer $parent_id
 */
class Post extends CActiveRecord{
	
	/**
	 * @var int 
	 */
	public $parent_id;
	
	/**
	 * Behavior
	 * @return array
	 */
	public function behaviors(){
		return array(
			'nestedSetBehavior' => array(
				'class'          => 'application.components.NestedSetBehavior',
				'leftAttribute'  => 'lft',
				'rightAttribute' => 'rgt',
				'levelAttribute' => 'level',
			),
		);
	}
	
	/**
	 * @return string the associated database table name
	 */
	public function tableName(){
		return 'post';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules(){
		return array(
			array('lft, rgt, level', 'numerical', 'integerOnly'=>true),
			array('date', 'safe'),
			array('autor, text ', 'required'),
			array('text', 'match', 'pattern' => '/^[A-Za-zА-Яа-я0-9\.\,\(\)]+$/u', 'message'=> 'Есть некорректные символы!'),
			array('text', 'length', 'max'=>1020),
			array('autor', 'length', 'max'=>100),
			array('id, autor, text, date, lft, rgt, level', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations(){
		return array(
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels(){
		return array(
			'id'    => 'ID',
			'autor' => 'Автор',
			'text'  => 'Комментарий',
			'date'  => 'Дата',
			'lft'   => 'Lft',
			'rgt'   => 'Rgt',
			'level' => 'Level',
			'alias' => 'Alias',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search(){
		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id);
		$criteria->compare('autor',$this->autor,true);
		$criteria->compare('text',$this->text,true);
		$criteria->compare('date',$this->date,true);
		$criteria->compare('lft',$this->lft);
		$criteria->compare('rgt',$this->rgt);
		$criteria->compare('level',$this->level);
		$criteria->compare('alias',$this->alias,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * @param string $className active record class name.
	 * @return Post the static model class
	 */
	public static function model($className=__CLASS__){
		return parent::model($className);
	}
	
	/**
	 * Создаем корневой пост или возвращаем уже имеющийся
	 * @param Post $model
	 * @return mixed
	 */
	public static function getRoot(Post $model){
		$dependency = new CDbCacheDependency('SELECT max("date") FROM post');
		$root = $model->roots()->cache(60*60*6, $dependency)->find();
		if (! $root){
			$model->autor = 'root';
			$model->text = 'Root';
			$model->saveNode();
			$root = $model->roots()->find();
		}
		return $root;
	}

}

protected/controllers/PostController.php
<?php

class PostController extends Controller {
	
	/**
	 * @var string 
	 */
	public $layout='//layouts/main';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
		);
	}

	/**
	 * Создаем пост
	 */
	public function actionCreate(){
		$model = new Post;
		$parent_id = Yii::app()->request->getParam('parent_id',1);
		
		if(isset($_POST['Post'])){
			$model->attributes = $_POST['Post'];
			$current_root = Post::model()->findByPk((int)$_POST['Post']['parent_id']);
			
			if($model->appendTo($current_root)){
				$this->redirect('/');
			}
		}
 
		$this->render('create',array(
			'model'      =>$model,
			'parent_id'  => $parent_id,
			'id'         => null,
		));
	}



	/**
	 * Deletes a particular model.
	 * If deletion is successful, the browser will be redirected to the 'admin' page.
	 * @param integer $id the ID of the model to be deleted
	 */
	public function actionDelete($id){
		$this->loadModel($id)->deleteNode();
		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
	}

	/**
	 * Удалить все записи
	 */
	public function actionDelete_all(){
		Yii::app()->db->createCommand('TRUNCATE post')->query();
		// if AJAX request (triggered by deletion via admin grid view), we should not redirect the browser
		if(!isset($_GET['ajax']))
			$this->redirect(isset($_POST['returnUrl']) ? $_POST['returnUrl'] : array('index'));
	}

	/**
	 * Все посты
	 */
	public function actionIndex(){
		$model = new Post;
		$root = Post::getRoot($model);
		$dependency = new CDbCacheDependency('SELECT max("date") FROM post');
		$posts = $root->descendants()->cache(60*60*6, $dependency)->findAll();
		$this->render('index',array(
			'root'  => $root,
			'posts' => $posts,
		));
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param integer $id the ID of the model to be loaded
	 * @return Post the loaded model
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model=Post::model()->findByPk($id);
		if($model===null){
			throw new CHttpException(404,'Такой страницы нет.');
		}
		return $model;
	}
}

protected/views/layouts/column1.php
<?php $this->beginContent('/layouts/main'); ?>
<div class="container">
	<div id="content">
		<?php echo $content; ?>
	</div><!-- content -->
</div>
<?php $this->endContent(); ?>

protected/views/layouts/column2.php
<?php $this->beginContent('/layouts/main'); ?>
<div class="container">
	<div class="span-18">
		<div id="content">
			<?php echo $content; ?>
		</div><!-- content -->
	</div>
	<div class="span-6 last">
		<div id="sidebar">
			<?php if(!Yii::app()->user->isGuest) $this->widget('UserMenu'); ?>

			<?php $this->widget('TagCloud', array(
				'maxTags'=>Yii::app()->params['tagCloudCount'],
			)); ?>

			<?php $this->widget('RecentComments', array(
				'maxComments'=>Yii::app()->params['recentCommentCount'],
			)); ?>
		</div><!-- sidebar -->
	</div>
</div>
<?php $this->endContent(); ?>

protected/views/layouts/main.php
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta name="language" content="en" />

	<!-- blueprint CSS framework -->
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/screen.css" media="screen, projection" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/print.css" media="print" />
	<!--[if lt IE 8]>
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/ie.css" media="screen, projection" />
	<![endif]-->

	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/main.css" />
	<link rel="stylesheet" type="text/css" href="<?php echo Yii::app()->request->baseUrl; ?>/css/form.css" />

	<title><?php echo CHtml::encode($this->pageTitle); ?></title>
</head>

<body>

<div class="container" id="page">

	<div id="header">
		<div id="logo"><?php echo CHtml::encode(Yii::app()->name); ?></div>
	</div><!-- header -->

	<div id="mainmenu">
	</div><!-- mainmenu -->

	<?php $this->widget('zii.widgets.CBreadcrumbs', array(
		'links'=>$this->breadcrumbs,
	)); ?><!-- breadcrumbs -->
	<div style="margin: 10px;">
		<?php echo $content; ?>
	</div>
	<div id="footer">
		Copyright &copy; <?php echo date('Y'); ?> by My Company.<br/>
		All Rights Reserved.<br/>
		<?php echo Yii::powered(); ?>
	</div><!-- footer -->

</div><!-- page -->

</body>
</html>

protected/views/post/_form.php
<?php
/* @var $this PostController */
/* @var $model Post */
/* @var $form CActiveForm */
?>

<div class="form">

<?php $form=$this->beginWidget('CActiveForm', array(
	'id'                     => 'post-form',
	'enableClientValidation' => TRUE,
)); ?>
	<?=$form->hiddenField($model, 'parent_id', $htmlOptions=array('value'=>$parent_id)) ?>
	<?= $form->errorSummary($model); ?>

	<div class="row">
		<?= $form->labelEx($model,'autor'); ?>
		<?= $form->textField($model,'autor',array('size'=>60,'maxlength'=>200)); ?>
		<?= $form->error($model,'autor'); ?>
	</div>

	<div class="row">
		<?= $form->labelEx($model,'text'); ?>
		<?= $form->textArea($model,'text',array('rows'=>6, 'cols'=>50)); ?>
		<?= $form->error($model,'text'); ?>
	</div>
	<div class="row buttons">
		<?= CHtml::submitButton($model->isNewRecord ? 'Создать' : 'Сохранить'); ?>
	</div>

<?php $this->endWidget(); ?>

</div><!-- form -->

protected/views/post/create.php
<?php
/* @var $this PostController */
/* @var $model Post */

$this->breadcrumbs=array(
	'Posts' => array('index'),
	'Create',
);
?>

<h1>Новый коммент</h1>

<?php $this->renderPartial('_form', array('model'=>$model,'parent_id' => $parent_id)); ?>

protected/views/post/index.php
<div  class="index">
	<?php
	$this->breadcrumbs = array(
		'Посты',
	);
	?>
	<h1>Посты</h1>
	<?= $this->renderPartial('menu')?>
	
	<?php if ($posts): ?>
		<?php $level = 0; ?>
		<?php foreach($posts as $n => $post): ?>
			<?php if ($post->level == $level): ?>
				</li>
			<?php elseif($post->level > $level): ?>
				<ul>
			<?php else: ?>
				</li>
				<?php for($i = $level - $post->level; $i; $i--):?>
					</ul>
					</li>
				<?php endfor;?>
			<?php endif; ?>
			<li>
				<?= $this->renderPartial('view', array('model'=>$post))?>
				<?php
					$level = $post->level;
				?>
		<?php endforeach; ?>
		<?php for ($i = $level; $i; $i--): ?>
			</li>
			</ul>
		<?php endfor; ?>
	<?php else: ?>
		<div>
			А вот нету комментариев ;(
		</div>
	<?php endif; ?>
	<?= $this->renderPartial('menu')?>
</div>

protected/views/post/menu.php
<div class="menu">
	<a class="create" title="Новый коммент" href="<?= Yii::app()->createUrl('/post/create') ?>">Комментировать</a>
	<a class="delete_all" title="Удалить все" href="<?= Yii::app()->createUrl('/post/delete_all') ?>">Удалить все</a>
</div>

protected/views/post/view.php
<div class="post" >
	<div>
		<strong>Автор: <?= $model->autor?>	( Дата: <?= $model->date?> )</strong>
	</div>
	<div>
		<?= $model->text?>
	</div>
	<div>
		<a class="create" title="Новый коммент" href="<?= Yii::app()->createUrl('/post/create', array('parent_id' => $model->id)) ?>">Комментировать</a>
		<a class="delete" title="Удалить" href="<?= Yii::app()->createUrl('/post/delete',array('id' => $model->id)) ?>">Удалить</a>
	</div>
</div>